# Generated by Django 5.0.13 on 2025-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_livescore_matchdetails_nextmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='livescore',
            name='batsman',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='batsman_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='bowler',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='last_ball',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='last_ball_runs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='runner',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='runner_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
