# Generated by Django 5.0.13 on 2025-05-03 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_livescore_batsman_livescore_batsman_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livescore',
            name='batsman',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='batsman_score',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='bowler',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='last_ball',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='last_ball_runs',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='runner',
        ),
        migrations.RemoveField(
            model_name='livescore',
            name='runner_score',
        ),
        migrations.RemoveField(
            model_name='nextmatch',
            name='match',
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='Score1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='score1', to='main.score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdetails',
            name='Score2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='score2', to='main.score'),
            preserve_default=False,
        ),
    ]
