# Generated by Django 5.0.13 on 2025-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_livescore_batsman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livescore',
            name='batsman',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='batsman_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livescore',
            name='bowler',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='last_ball_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livescore',
            name='runner',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livescore',
            name='runner_score',
            field=models.IntegerField(default=0),
        ),
    ]
