# Generated by Django 5.0.13 on 2025-05-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_livescore_batsman_livescore_batsman_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.CharField(max_length=100)),
                ('overs', models.FloatField()),
                ('wickets', models.IntegerField()),
                ('batsman', models.CharField(max_length=100)),
                ('batsman_score', models.IntegerField(default=0)),
                ('runner', models.CharField(max_length=100)),
                ('runner_score', models.IntegerField(default=0)),
                ('bowler', models.CharField(max_length=100)),
                ('last_ball_runs', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
            ],
        ),
        migrations.DeleteModel(
            name='NextMatch',
        ),
    ]
