# Generated by Django 5.0.13 on 2025-05-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_livescore_ball_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterField(
            model_name='livescore',
            name='batsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsman', to='main.player'),
        ),
        migrations.AlterField(
            model_name='livescore',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner', to='main.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.team'),
        ),
    ]
