# Generated by Django 5.0.13 on 2025-05-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_player_age_remove_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livescore',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='main.player'),
        ),
    ]
