# Generated by Django 5.0.13 on 2025-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livescore',
            name='id',
        ),
        migrations.AddField(
            model_name='livescore',
            name='idno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
