# Generated by Django 5.0.13 on 2025-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_livescore_id_livescore_idno_alter_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livescore',
            name='idno',
        ),
        migrations.AddField(
            model_name='livescore',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
