# Generated by Django 5.0.13 on 2025-05-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_livescore_idno_livescore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livescore',
            name='overs',
            field=models.FloatField(default=-0.1),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='match_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='main.team'),
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='player_of_the_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
