# Generated by Django 5.0.13 on 2025-05-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_livescore_overs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdetails',
            name='toss_decision',
        ),
        migrations.AlterField(
            model_name='matchdetails',
            name='toss_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_winner', to='main.team'),
        ),
    ]
