# Generated by Django 5.0.13 on 2025-05-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_matchdetails_toss_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetails',
            name='toss_decision',
            field=models.CharField(choices=[('bat', 'Bat'), ('bowl', 'Bowl')], default='NotSelected', max_length=100),
            preserve_default=False,
        ),
    ]
